[package]
name = "oxidant"
version = "0.1.0"
edition = "2021"

[lib]
name = "oxidant"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
encoding_rs = "0.8"
